nelmio_cors:
  defaults:
    allow_origin: ["http://localhost:3000"] # Origine autorisée
    allow_credentials: true
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: []
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    max_age: 3600
  paths:
    "^/api/": # Appliquer les règles CORS uniquement aux routes commençant par /api/
      allow_origin: ["http://localhost:3000"]
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_credentials: true
